aws:
  global:
    region: "ap-southeast-1"
    state_bucket: "terraform.nasir.id"

  network:
    vpc_name: "nasir-eks-vpc"
    description: "eks-vpc"
    cidr_block: "10.0.0.0/16"
    instance_tenancy: "default"
    enable_dns_support: true
    enable_dns_hostnames: true
    subnet_count: 2
    subnet_mask: "24"

  ec2:
    kafka: 
      name: "management-eks"
    instance_type: "t3.small"
    ami: "ami-0c1907b6d738188e5"
    root_block_device:
      volume_size : 50
      volume_type: "gp3"
      delete_on_termination: true
      encrypted: true
cloudflare:
  zone_id: "nasir.id"
  root: "@"
contabo:
  ip: "161.97.100.1"  
  
      
 


