aws:
  global:
    region: "ap-southeast-1"
    state_bucket: "terraform.nasir.id"

  network:
    vpc_name: "nasir-vpc"
    description: "eks-vpc"
    cidr_block: "10.1.0.0/16"
    instance_tenancy: "default"
    enable_dns_support: true
    enable_dns_hostnames: true
    subnet_count: 3
    subnet_mask: "24"
  s3:
    bucket_name_wordpress: "wordpress.nasir.id"
    bucket_name_backup: "backup.nasir.id"
    bucket_name_upload: "upload.nasir.id"
  acm:
    domain_name_assets: "assets.nasir.id" 
    create_route53_records: false
    validation_method: "DNS"
  cloudfront:
    domain_name_assets: "assets.nasir.id"   

  ec2:
    kafka: 
      name: "management-eks"
    instance_type: "t3.small"
    ami: "ami-0c1907b6d738188e5"
    root_block_device:
      volume_size : 50
      volume_type: "gp3"
      delete_on_termination: true
      encrypted: true
cloudflare:
  zone_id: "nasir.id"
  root: "@"
contabo:
  ip: "161.97.100.1"  
  
      
 


