"""
Handles profile photo upload to S3 and cartoon generation via Google Gemini.
S3 paths:
  avatars/{user_id}/{date}-original.jpg     — uploaded photo
  avatars/{user_id}/{date}-avatar.jpg       — cartoon-style version (Gemini generated)
"""
import io, os, base64
from datetime import datetime
import boto3
import google.generativeai as genai
from PIL import Image

_s3 = None

def _get_s3():
    global _s3
    if _s3 is None:
        _s3 = boto3.client(
            's3',
            aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
            aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
            region_name=os.getenv('AWS_REGION', 'ap-southeast-1'),
        )
    return _s3

BUCKET   = os.getenv('S3_BUCKET_NAME')
CDN_BASE = os.getenv('S3_CDN_BASE', '')
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')

if GOOGLE_API_KEY:
    genai.configure(api_key=GOOGLE_API_KEY)


def _s3_url(key: str) -> str:
    base = CDN_BASE.rstrip('/') or f"https://{BUCKET}.s3.amazonaws.com"
    return f"{base}/{key}"


def _get_date_string() -> str:
    """Get current date in YYYYMMDD format."""
    return datetime.now().strftime('%Y%m%d%H%M%S')


def upload_original(file_bytes: bytes, user_id: int, content_type: str) -> str:
    """Upload original image to S3 with date prefix."""
    ext = 'jpg' if 'jpeg' in content_type.lower() else content_type.split('/')[-1] if '/' in content_type else 'jpg'
    date_str = _get_date_string()
    key = f"avatars/{user_id}/{date_str}-original.{ext}"
    
    _get_s3().upload_fileobj(
        io.BytesIO(file_bytes), BUCKET, key,
        ExtraArgs={'ContentType': content_type},
    )
    return _s3_url(key)


def generate_cartoon(file_bytes: bytes, user_id: int, age: int = None, race: str = "Asian") -> str | None:
    """Generate a Pixar-style cartoon avatar using Google Gemini and upload to S3."""
    if not GOOGLE_API_KEY:
        print("[avatar_service] GOOGLE_API_KEY not set, skipping cartoon generation")
        return None
    
    try:
        # Convert file bytes to PIL Image to send to Gemini
        image = Image.open(io.BytesIO(file_bytes))
        
        # Create prompt based on user age and race
        age_str = f"a {age} year-old" if age else "an adult"
        prompt = f"A Pixar-style 3D cartoon portrait of a {race} man in his {age_str} based on attached image. Make it cute, colorful, and friendly."
        
        # Generate cartoon image with Gemini
        model = genai.GenerativeModel('gemini-2.0-flash')
        response = model.generate_images(
            prompt=prompt,
            number_of_images=1,
            model='imagen-3.0-generate-002',
        )
        
        if not response or not response.generated_images:
            print("[avatar_service] No image generated by Gemini")
            return None
        
        # Get image bytes from Gemini response
        cartoon_image_bytes = response.generated_images[0]._image_bytes
        
        # Upload to S3
        date_str = _get_date_string()
        key = f"avatars/{user_id}/{date_str}-avatar.jpg"
        
        _get_s3().upload_fileobj(
            io.BytesIO(cartoon_image_bytes), BUCKET, key,
            ExtraArgs={'ContentType': 'image/jpeg'},
        )
        
        return _s3_url(key)
        
    except Exception as e:
        print(f"[avatar_service] Cartoon generation failed: {e}")
        return None
