apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app-deployment
  namespace: nasir 
  labels:
    app: gke-app 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: gke-app 
  template:
    metadata:
      labels:
        app: gke-app 
    spec:
      containers:
      - name: gke-app 
        image: asia-southeast1-docker.pkg.dev/nasir-456515/nasir/gke-app:latest
        ports:
        - containerPort: 8000 
        env:
        - name: DJANGO_SECRET_KEY 
          valueFrom:
            secretKeyRef:
              name: django-secret-key
              key: SECRET_KEY 
        resources:
        
          requests:
            cpu: "100m" 
            memory: "128Mi" 
          limits:
            cpu: "200m" 
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: / 
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10 
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: / 
            port: 8000
          initialDelaySeconds: 15 
          periodSeconds: 5 
          timeoutSeconds: 3 
          failureThreshold: 2 