name: Build and Push Docker Image to Artifact Registry

on:
  push:
    paths:
      - 'apps/gke-django/**'
      - '.github/workflows/app-gke-build-push.yml'
    branches:
      - main    
  pull_request:
    paths:
      - 'apps/gke-django/**'
      - '.github/workflows/app-gke-build-push.yml'   
    branches:
      - main

env:
  PROJECT_ID: nasir-456515 
  AR_REPO: nasir           
  AR_LOCATION: asia-southeast1 
  IMAGE_NAME: gke-app      

jobs:
#   gcp-config:
#     name: GCP Configuration
#     runs-on: [self-hosted, contabo]
#     steps:
#       - name: Configure GCP
#         env:
#           VAULT_ADDR: "http://127.0.0.1:8200"  # Use http:// instead of https://
#           VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}      
#         run: |
#           pwd
#           whoami
#           /home/nasir/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=gcp-service-account.json
#           /home/nasir/google-cloud-sdk/bin/gcloud config set project nasir-456515
#           echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-service-account.json" >> $GITHUB_ENV    
  build-and-push:
    runs-on: [self-hosted, contabo]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Submit Build to Google Cloud Build
      run: |
        /home/nasir/google-cloud-sdk/bin/gcloud auth list
        # /home/nasir/google-cloud-sdk/bin/gcloud builds submit . --project=${{ env.PROJECT_ID }} --config=apps/gke-django/cloudbuild.yaml
        cd apps/gke-django
        service docker status
        docker build -t django-app:latest .
        docker push asia-southeast1-docker.pkg.dev/nasir-456515/nasir/django-app:latest
    - name: Verify Image Push (Optional)
      run: |
        echo "Image push command submitted to Cloud Build successfully."
        echo "Check Cloud Build logs in GCP console for detailed status."


