name: Deploy nasir.id

on:
  push:
    paths:
      - 'app/nasir-id/*.*'
    branches:
      - main
  pull_request:
    paths:
      - 'apps/nasir-id/*.*'
    branches:
      - main

jobs:
  deploy-nginx:
    runs-on: [self-hosted, contabo]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to nginx
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "Remove existing code"
        echo "$SSH_PASSWORD" | sudo -S rm -r /var/www/html/*.*
        echo "$SSH_PASSWORD" | sudo cp "app/nasir-id" "/var/www/html/"
  