name: Build and Push Docker Image to Artifact Registry

on:
  push:
    paths:
      - 'apps/gke-django/**'
      - '.github/workflows/app-gke-build-push.yml'
    branches:
      - main    
  pull_request:
    paths:
      - 'apps/gke-django/**'
      - '.github/workflows/app-gke-build-push.yml'   
    branches:
      - main

env:
  PROJECT_ID: nasir-456515 
  AR_REPO: nasir           
  AR_LOCATION: asia-southeast1 
  IMAGE_NAME: gke-app      

jobs:
  build-and-push:
    runs-on: [self-hosted, contabo]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2          
    - name: Configure Docker for Artifact Registry
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }} 
      run: |
        /home/nasir/google-cloud-sdk/bin/gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-southeast1-docker.pkg.dev
        #echo "$SSH_PASSWORD" | sudo -S gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin asia-southeast1-docker.pkg.dev

        echo $GOOGLE_APPLICATION_CREDENTIALS
        cat $GOOGLE_APPLICATION_CREDENTIALS
    - name: Build and Push Docker Image
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  
      run: |
        /home/nasir/google-cloud-sdk/bin/gcloud auth list
        # /home/nasir/google-cloud-sdk/bin/gcloud builds submit . --project=${{ env.PROJECT_ID }} --config=apps/gke-django/cloudbuild.yaml
        cd apps/gke-django
        service docker status
        pwd
        ls -la
        /home/nasir/google-cloud-sdk/bin/gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        echo "$SSH_PASSWORD" | sudo -S docker build -t asia-southeast1-docker.pkg.dev/nasir-456515/nasir/django-app:latest .
        echo "$SSH_PASSWORD" | sudo -S docker push asia-southeast1-docker.pkg.dev/nasir-456515/nasir/django-app:latest
        #/usr/bin/docker build -t asia-southeast1-docker.pkg.dev/nasir-456515/nasir/django-app:latest .
        #/usr/bin/docker push asia-southeast1-docker.pkg.dev/nasir-456515/nasir/django-app:latest
    - name: Verify Image Push (Optional)
      run: |
        echo "Image pushed successfully to asia-southeast1-docker.pkg.dev/nasir-456515/nasir/django-app:latest"


