name: 'AWS Plan'

on:
  push:
    # branches: [ '**' ] 
    branches: 
      # - '**'
      # - '!main'
      - 'main'
    paths:
      - 'gcp/services/**.tf' 
      - 'gcp/services/**.tfvars'  
      - '.github/workflows/gcp-plan.yml'

env:
  TF_VERSION: '1.11.4'  
  GCP_REGION: 'asia-southeast1'  

jobs:

  gcp-config:
    name: GCP Configuration
    runs-on: [self-hosted, contabo]
    steps:
      - name: Configure GCP
        env:
          VAULT_ADDR: "http://127.0.0.1:8200"  # Use http:// instead of https://
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}      
        run: |
          pwd
          whoami
          vault kv get kv/gcp
          vault kv get -field=key kv/gcp > gcp-service-account.json
          /home/nasir/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=gcp-service-account.json
          /home/nasir/google-cloud-sdk/bin/gcloud config set project nasir-456515
  detect-changed-dirs:
    name: Detect Changed Directories
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.find-dirs.outputs.dirs }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Find Changed Terraform Directories
        id: find-dirs
        run: |
          # Handle different event types
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Processing Pull Request event"
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.sha }}"
            
            if [ -z "$BASE_SHA" ] || [ "$BASE_SHA" = "0000000000000000000000000000000000000000" ]; then
              echo "Base SHA is empty or zero. Using all terraform files."
              CHANGED_FILES=$(find gcp/services -type f -name "*.tf" -o -name "*.tfvars" | sort)
            else
              echo "Comparing $BASE_SHA with $HEAD_SHA"
              CHANGED_FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" | grep -E '^gcp/services/.*\.(tf|tfvars)$' || echo "")
            fi
            
          elif [ "${{ github.event_name }}" == "push" ]; then
            echo "Processing Push event"
            BEFORE_SHA="${{ github.event.before }}"
            AFTER_SHA="${{ github.event.after }}"
            
            if [ -z "$BEFORE_SHA" ] || [ "$BEFORE_SHA" = "0000000000000000000000000000000000000000" ]; then
              echo "Before SHA is empty or zero. Getting all committed files."
              CHANGED_FILES=$(git ls-tree --name-only -r HEAD | grep -E '^gcp/services/.*\.(tf|tfvars)$' || echo "")
            else
              echo "Comparing $BEFORE_SHA with $AFTER_SHA"
              CHANGED_FILES=$(git diff --name-only "$BEFORE_SHA" "$AFTER_SHA" | grep -E '^gcp/services/.*\.(tf|tfvars)$' || echo "")
            fi
          else
            echo "Processing other event type"
            CHANGED_FILES=$(find gcp/services -type f -name "*.tf" -o -name "*.tfvars" | sort)
          fi
          
          # Process the changed files to get directories
          if [ -n "$CHANGED_FILES" ]; then
            echo "Found changed files:"
            echo "$CHANGED_FILES"
            DIRS=$(echo "$CHANGED_FILES" | xargs -I{} dirname {} 2>/dev/null | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))' || echo "[]")
          else
            echo "No changed terraform files detected"
            DIRS="[]"
          fi
          
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT
          echo "Changed directories: $DIRS"
  

  terraform-plan:
    name: Terraform Plan
    needs: detect-changed-dirs, gcp-config
    if: ${{ needs.detect-changed-dirs.outputs.dirs != '[]' }}
    runs-on: [self-hosted, contabo]
    strategy:
      matrix:
        directory: ${{ fromJSON(needs.detect-changed-dirs.outputs.dirs) }}
      fail-fast: false
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure backend.conf
        run: |
          pwd
          cd gcp
          ls -la
          state_bucket=$(yq e '.global.state_bucket' config.yaml)
          sed -i "s/^bucket = .*/bucket = \"${state_bucket}\"/" backend.conf
          sleep 100
          cat backend.conf                

      - name: Terraform Init
        working-directory: ${{ matrix.directory }}
        run: |
          pwd
          cp ../../backend.conf .
          cat backend.conf
          terraform init -backend-config=backend.conf

      - name: Terraform Validate
        working-directory: ${{ matrix.directory }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ matrix.directory }}
        run: terraform plan -no-color
        continue-on-error: true
        
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1